version: '3'
services:

  reverse-proxy:
    image: 'gamezeug/reverse-proxy'
    ports:
      - '80:80'
    env_file:
      - reverse-proxy/nginx.env
    networks:
      - frontend

  portal:
    image: 'artun/gamezeug-portal'
    ports:
      - '8080:80'
    networks:
      - frontend

  tables-frontend:
    image: 'artun/gamezeug-tables'
    ports:
      - '8082:4200'
    networks:
      - frontend

  chat-frontend:
    image: 'artun/gamezeug-chat-frontend'
    ports:
      - '8083:80'
    networks:
      - frontend

  auth-server:
    image: 'artun/gamezeug-auth-server'
    ports:
     - '8081:8080'
    env_file:
      - gamezeug-auth-server.env

networks:
  frontend:
    driver: bridge